project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Fiorella Guillen"
  date: "28/03/2025"
  navbar:
     logo: "images/casa_logo.jpg"
     collapse: true
     collapse-below: lg
     background: light
     search: true
     right:
      - icon: github
        href: https://github.com/fiorellaguillen
      - icon: linkedin
        href: https://www.linkedin.com/in/fiorellaguillenh/
     
  sidebar:
    title: "Learning Diary"
    style: floating
    reader-mode: true
    collapse: true
    pinned: false
    
  
  chapters:
    - index.qmd
    - W1_Introduction.qmd
    - W2_Portfolio.qmd
    - W3_RemoteSensingData.qmd
    - W4_Policy.qmd
    - W6_GEE.qmd
    - W7_Classification.qmd
    - W8_Classification2.qmd
    - W9_SAR.qmd
    - references.qmd

favicon: "images/casa_logo.jpg"
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

