project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Fiorella Guillen"
  date: "03/03/2025"
  chapters:
    - index.qmd
    - W1_Introduction.qmd
    - W2_Portfolio.qmd
    - W3_RemoteSensingData.qmd
    - W4_Policy.qmd
    - W6_GEE.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

