---
title: "Welcome"
format: html
---

# Introduction {.unnumbered}

**Hello world!**

This Learning Diary is part of the CASA0023 module, *Remotely Sensing Cities and Environments*, which I’m taking as part of the MSc Urban Spatial Science at UCL. Here, you'll find weekly entries summarizing key takeaways from each lecture, examples of practical applications, and my personal reflections.

**But first, let me introduce myself!**

My name is Fiorella, and I’m currently pursuing an MSc in Urban Spatial Science. Back in 2021, I graduated as an architect and urbanist in Peru. Since then, I have developed a strong interest in sustainability, climate change, water resources, and urban settlements, particularly how these factors affect urban and natural environments. As an example, during my undergraduate thesis, I focused on assessing changes in a river in the Peruvian Amazon, accelerated by climate change, and proposed solutions to the urban challenges that emerged from these changes.

Since graduating, I have worked in the public sector, contributing to Lima’s Rimac River renaturalization project. This role involved urban analysis, master planning, urban design, and policy implementation, with a strong emphasis on risk prevention, and nature-based solutions.

While I have some basic experience using Earth Observation (EO) and remote sensing to address topics like those mentioned above, my approach has been largely empirical. That’s why I find this module to be an exciting opportunity to deepen my knowledge of these tools and processes, enabling me to better inform policies and urban solutions in future projects or research.

I am particularly interested in how these technologies can be applied to urban challenges in the Global South, where they are often underutilized due to knowledge gaps. That's why, throughout this diary, my reflections will aim to connect these tools to my background and interests, as well as explore their real-world applications in contexts similar to my country’s.

And if you are curious about my previous projects, here you can have a glimpse at them!

{{< video https://youtu.be/yqOHqQDk1jY >}}

{{< video https://www.youtube.com/watch?v=g--IDi_i3xs>}}
