---
title: "An Introduction to Remote Sensing"
format: html
---

## **Summary**

The *Plan Integral de Reconstrucción con Cambios* (PIRCC) is a strategy developed by the peruvian government to rebuild and strengthen areas affected by *El Niño Costero*. Its goal is not just to repair damaged infrastructure but also to make communities more resilient against future disasters. The plan promotes sustainable urban development and better risk management, recognizing that prevention costs only a fraction of post-disaster reconstruction. Given the increasing impact of climate change, the PIRCC highlights the need to prepare for extreme weather events rather than just reacting to them.

That said, while the plan includes mitigation measures, these have mostly focused on building flood defenses, dikes, and urban development projects in affected cities. What’s missing is a more integrated approach to long-term risk monitoring, tools that could provide real-time data and analysis to guide urban planning and infrastructure decisions. Without that, rebuilding efforts risk being reactive rather than strategic, making it harder to anticipate and adapt to future climate threats.

## **Applications**

Considering this, it would be relevant to create a monitoring tool through Remote Sensing that can analyse previous years' affected areas by El Niño and with that information classify land risk...

## **Reflections**
